### ISSUE TITLE
[REQUEST] Pola-rs

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#1029]
Pola-rs https://github.com/open-ce/open-ce/issues/889
Website: https://www.pola.rs/
Source: https://github.com/pola-rs/polars

**Comment by Aman-Surkar** [comment]
When trying to build the recipe, the conda complains about `Error: package/name missing` in the `meta.yaml`. It is not picking up the `polars_variant` from `conda_build_config.yaml`. Due to this issue, the polars variants were segregated into 3 different directories, and were listed in `conda_build_config.yaml` in config directory.

**Comment by Aman-Surkar** [comment]
The other issues faced while building polars are listed in https://github.com/open-ce/open-ce/issues/1260 issue
