### ISSUE TITLE
Produce Conda Env File as part of `build_env`

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#45]
After #44 is complete it would be good to have the build scripts produce a conda env file that can be used to install the conda environment that was just validated and built.

This should be produced separate from the actual build process, similar to the DAG production, so that there is flexibility to integrate into future tools.

The environment file should be displayed at the end of the `build_env` run so that users can use that to setup a new conda environment.

**Comment by npanpaliya** [comment]
I just tried to write small prototype code using BuildTree class that would generate an env file and I'm able to create an env from it.

**Comment by bethune-bryant** [comment]
@npanpaliya Thanks for picking this up!

You should be able to just use the run_dependencies member in the BuildTree class:
https://github.com/open-ce/open-ce/blob/cfbe5c9b5cd84bc747745681d77030473c605acb/open-ce/build_tree.py#L53

Also, something I left out of the original issue description is that we want to display the environment file at the end of the `build_env` run so that users can use that to setup their new conda environment.(I added it there also)

**Comment by npanpaliya** [comment]
Thanks @bethune-bryant . Yes, I'll use `run_dependencies`. 
Also, thanks for clarifying my doubt which I was about to ask here about conda env file generation. My doubt was should it be optional and controlled via command line argument to build_env.py script OR it should always be generated.

**Comment by npanpaliya** [comment]
Also, one more point to confirm - There will be multiple conda env file based on build_types (2) and python_versions (3). So, at max 2*3=6 conda env files that we will be writing.

**Comment by npanpaliya** [comment]
@jayfurmanek , @bnemanich ,@bethune-bryant - 
While working on this, I've come across a couple of problems - 

1.  BuildTree specific
   a. In BuildTree, we haven't considered conda_build_config.yaml which is inside config directory while `_get_package_dependencies` so that the versions of packages like `_xgboost_select` or `_tensorflow_select` are read. I've fixed this.
  b. run_dependencies gives runtime dependencies of build time dependencies of a package. For e.g. bazel's build time dependency is java-openjdk whose runtime dependencies are all those nss*, etc. from cdts-feedstock. So, ideally those packages aren't required for bazel to run. I think this can be handled by adding some tag for master package in each environment file. And run time dependencies for that master package should be taken to create conda env file. More thoughts or suggestions are needed on this.

2. Inconsistency in our recipes while specifying package name and version in requirement section.
 Number of spaces between package name and version varies in each recipe. As a result, dependency name like `cudatoolkit 10.2.*` and `cudatoolkit        10.2.*` are treated differently while inserting in the set.

I'm working on above problems along with the main issue. Please let me know if you have any thoughts or suggestions on this.

**Comment by npanpaliya** [comment]
Status of problems mentioned in above comment - 
1 BuildTree Specific
   a.  Fixed
   b. In progress
2. Fixed

**Comment by bnemanich** [comment]
This was completed as part of #94.
