### ISSUE TITLE
[REQUEST] jax support

### ISSUE THREAD

**Issue by feifzhou** [open-ce/open-ce#549]
**Is your feature request related to a problem? Please describe.**
Jax is becoming a very powerful and popular machine learning tool. It would great to be able to install it on powerpc platforms.

**Describe the solution you'd like**
Include jax in a future release

**Describe alternatives you've considered**
I tried to compile it but with no luck

**Additional context**
Some people reported success, others not so lucky. See

https://github.com/google/jax/issues/4493

**Comment by EmergentOrder** [comment]
+1. Was able to compile and install jax / jaxlib directly on ppc64le, but with many test failures and crashes with seg fault in my use case.
So it'd be great to see in open-ce.

**Comment by alexlang74** [comment]
Thanks for the feedback! Currently targeted for OpenCE 1.9

**Comment by npanpaliya** [comment]
@EmergentOrder - Did you try building it directly from source or built its conda recipe from conda-forge?

**Comment by EmergentOrder** [comment]
@npanpaliya Directly from source.

**Comment by alexlang74** [comment]
Will be addressed in OpenCE 1.9

**Comment by alexlang74** [comment]
Delivered in OpenCE 1.9. Looking forward to your feedback!

**Comment by amccaugh** [comment]
Thank you so much, this is fantastic!  I was able to get jax installed on our Power9 cluster with CUDA 11.8 by running with the following command:

`conda install -c https://ftp.osuosl.org/pub/open-ce/current/ jax=*=*cuda11.8* cudnn`

One followup question : would it be possible to build one of the more recent jax versions and/or against CUDA 12?  I so far have two issues:  (1) I occasionally get segfaults that I suspect are due to CUDA 11.8, and (2) there are a few functions implemented within the last few versions that would be very nice to have
