### ISSUE TITLE
[FEEDSTOCK REQUEST] cryptography package that supports FIPS

### ISSUE THREAD

**Issue by alexlang74** [open-ce/open-ce#753]
Compliance with the FIPS "standard" requires that all packages that are used for encryption use only FIPS-certified encryption packages. Red Hat provides a FIPS-certified OpenSSL library. However, cryptography from Anaconda is not built against RedHat's OpenSSL library. Hence, when running in a FIPS-enabled OpenShift cluster, cryptography returns ciphers that are not FIPS-compliant, like MD5.

The request:
- build cryptography against RedHat's OpenSSL library 1.1.1k (exact version TBD). This will require that the library is also present _at runtime_ . 
- provide cryptography in a separate conda channel. This way, OpenCE consumers can decide whether to stick with anacondas cryptography, or use the one from OpenCE

**Comment by rolweber** [comment]
Please do not try to pin the RedHat OpenSSL version. We'd have to wait for a new Open CE release every time RedHat updates their package.

**Comment by alexlang74** [comment]
We will need to provide this for both Python 3.9 and Python 3.10.

**Comment by rolweber** [comment]
_We discussed this in a meeting yesterday. Summary:_

Our goal for the FIPS support is to replace the openssl package from Anaconda with the one from RedHat. The binaries of cryptography are affected by the OpenSSL package used at build time, through include files and/or capability detection. So the bigger picture for building cryptography with FIPS support is:

1. Create an `openssl` (stub) package, which symlinks or otherwise refers to the RedHat OpenSSL library and header files.
   - To satisfy the dependencies of other packages expecting `openssl`, this one should follow the version numbering scheme of the Anaconda openssl package.
   - To avoid rebuilding for every new release of the Anaconda openssl package, maybe use `1.1.1z` as the version number? Or something else that satisfies "less than 1.1.2, at least 1.1.1*x*" where *x* means an incrementing lower-case letter, currently `s`. 
   - The build string should be distinct from those of the Anaconda openssl package, so that we can explicitly depend on the stub. For example `openssl=1.1.1z=*_fips` or something like that

3. Build the cryptography package on RedHat, using the `openssl` (stub) package from step 1.
   - The package should explicitly depend on the stub version of openssl, using the build string. Users should not be able to replace the openssl stub with an Anaconda build without also replacing the cryptography package.

**Comment by alexlang74** [comment]
ToDo: ensure that the install is synced with RocketCE, to ensure they create the same, separate channel.

**Comment by alexlang74** [comment]
Delivered as part of OpenCE 1.7. Will also come in OpenCE 1.9
