### ISSUE TITLE
[BUG] check if using NO_OF_MAKE_THREADS=128 is causing protobuf build issues on s390x

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#978]
check if recently added change - https://github.com/open-ce/open-ce/blob/main/envs/feedstock-patches/protobuf/0001-Use-LIMIT_BUILD_RESOURCES-flag-libprotobuf.patch#L20 is causing a build issue protobuf builds on s390x.

**Comment by ravigumm** [comment]
Yeah. When CPU_COUNT Is 4 on an s390x VM, trying out "make -j 128" seems to be causing consumption of lot of resources because of that much parallellism. The older code "make -j $CPU_COUNT" looks better in general to me for s390x. Am not sure if hardcoding the parallelism to 128 for ppc64le also is OK or not. Would it be better to make that number a multiple of CPU_COUNT if not just CPU_COUNT for ppc64le ?

**Comment by cdeepali** [comment]
yes for now, I am disabling the patch for s390x.
